services:
  postgres:
    image: postgres:16
    container_name: starter-template-pg
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mail-catcher:
    image: "axllent/mailpit:latest"
    ports:
      - ${MAIL_CATCHER_VIEW_PORT}:8025
      - ${MAIL_CATCHER_SERVER_PORT}:1025
volumes:
  postgres_data:
